name: Build LaTeX Document

# Запуск при пуше в основную ветку
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      # 1. Копируем файлы из репозитория в виртуальную машину
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Компиляция PDF
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          # Главный файл проекта
          root_file: main.tex
          # Используем pdflatex (как в Overleaf)
          compiler: pdflatex
          # Дополнительные аргументы (для работы с модулями и картинками)
          args: "-interaction=nonstopmode -halt-on-error -file-line-error"

      # 3. Сохранение готового PDF как артефакта GitHub
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: ORION-Instruction-PDF
          path: main.pdf
